In [1]:
import numpy as np
import pandas as pd
import random 

ratings = np.random.randint(1,6, size=(100, 4))
print("Original ratings\n")
print(ratings)

min_val = ratings.min()
max_val = ratings.max()
print("\nMinimum value in the ratings:")
print(min_val)
print("\nMaximum value in the ratings:")
print(max_val)


normalized_ratings = (ratings - min_val)/(max_val - min_val)
print("\nNormalize ratings:")
print(normalized_ratings)


average_per_employee = ratings.mean(axis=1)
print("\nAverage rating value:")
print(average_per_employee)

company_rating = average_per_employee.mean()
print("\naverage company rating:")
print(company_rating)

company_employee_avg = np.where(average_per_employee > company_rating)
print("\nAverage rating greater than employee:")
print(company_employee_avg[0])

Original ratings

[[2 4 3 5]
 [4 5 1 2]
 [2 3 4 1]
 [2 5 5 3]
 [3 1 3 1]
 [4 3 2 2]
 [4 1 2 2]
 [1 1 3 2]
 [5 4 3 1]
 [5 3 4 5]
 [1 2 2 1]
 [4 3 1 4]
 [2 5 5 2]
 [1 3 5 5]
 [5 4 5 4]
 [4 1 4 3]
 [1 4 4 2]
 [4 2 2 2]
 [4 1 2 5]
 [4 2 1 5]
 [5 2 3 3]
 [2 4 2 3]
 [2 2 2 3]
 [3 2 4 2]
 [3 2 1 3]
 [2 4 1 5]
 [4 1 2 1]
 [1 2 5 5]
 [4 4 4 2]
 [1 2 4 4]
 [3 4 1 3]
 [4 4 5 1]
 [3 2 5 5]
 [5 5 2 2]
 [1 1 5 5]
 [2 2 5 2]
 [1 2 4 5]
 [1 3 1 4]
 [3 3 3 4]
 [4 4 5 4]
 [4 4 4 1]
 [4 5 2 4]
 [2 3 4 4]
 [3 2 5 4]
 [4 4 2 1]
 [3 2 5 4]
 [3 4 1 3]
 [4 4 4 1]
 [3 4 5 5]
 [3 3 4 4]
 [4 1 5 2]
 [4 4 1 4]
 [5 3 2 1]
 [1 4 2 4]
 [3 1 1 2]
 [4 4 4 1]
 [4 5 5 3]
 [4 5 2 5]
 [1 5 5 4]
 [2 2 1 1]
 [2 2 5 1]
 [4 3 4 2]
 [3 4 4 2]
 [4 3 2 1]
 [4 1 2 1]
 [5 2 1 4]
 [1 3 4 4]
 [5 2 1 1]
 [3 3 1 4]
 [1 4 2 1]
 [2 5 5 2]
 [5 3 5 3]
 [2 5 3 3]
 [5 5 1 5]
 [1 2 2 1]
 [5 5 1 5]
 [3 5 1 3]
 [2 5 5 4]
 [2 2 1 5]
 [5 2 1 2]
 [5 5 3 5]
 [1 3 5 5]
 [5 4 3 5]
 [3 3 5 3]
 [2 4 2 2]
 [1 2 3 4]
 [1 5 5 3]
 [5 5 4 2]
 [4 4 3 4]
 [4

In [2]:
data = {
    "empid" : [1, 2, 3, 4, 5, 6],
    "department" : ["HR", "IT","Finance", "IT", "HR", "IT"],
    "quator": [1, 3, 1, 1, 4, 2],
    "performance_score" : [5, 4, 5, 4, 4, 3]

}

df = pd.DataFrame(data)
print(df)

   empid department  quator  performance_score
0      1         HR       1                  5
1      2         IT       3                  4
2      3    Finance       1                  5
3      4         IT       1                  4
4      5         HR       4                  4
5      6         IT       2                  3


In [4]:
group_dept = df.groupby("department")
print("\nGroup by department:")
print(group_dept.mean())

group_avg_quator = df.groupby(["department","quator"])["performance_score"].mean()
print("\n Quarter wise average: ")
print("\n",group_avg_quator)


pivot_df = df.pivot_table(
    index="department",
    columns="quator",
    values="performance_score",
    aggfunc="mean"
)

print("\nPivot Table:")
print(pivot_df)


Group by department:
            empid  quator  performance_score
department                                  
Finance       3.0     1.0           5.000000
HR            3.0     2.5           4.500000
IT            4.0     2.0           3.666667

 Quarter wise average: 

 department  quator
Finance     1         5.0
HR          1         5.0
            4         4.0
IT          1         4.0
            2         3.0
            3         4.0
Name: performance_score, dtype: float64

Pivot Table:
quator        1    2    3    4
department                    
Finance     5.0  NaN  NaN  NaN
HR          5.0  NaN  NaN  4.0
IT          4.0  3.0  4.0  NaN
